// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApROr8SlDPw6wQzgizNXJ41lfZmEzTGkU',
    appId: '1:848697741353:web:a09882fad49e0856010c38',
    messagingSenderId: '848697741353',
    projectId: 'pro1firebase-ce707',
    authDomain: 'pro1firebase-ce707.firebaseapp.com',
    storageBucket: 'pro1firebase-ce707.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiOPXeyvtf8Z8sZjU6gFpJZ0sGa0uPINs',
    appId: '1:848697741353:android:ca9835e213b50865010c38',
    messagingSenderId: '848697741353',
    projectId: 'pro1firebase-ce707',
    storageBucket: 'pro1firebase-ce707.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCBBbnc9A-k2u4drUz8WEDWahlNMdNG8Y',
    appId: '1:848697741353:ios:9d05f46b21ba1f70010c38',
    messagingSenderId: '848697741353',
    projectId: 'pro1firebase-ce707',
    storageBucket: 'pro1firebase-ce707.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );
}
